### ISSUE TITLE
binary_converter.py

### ISSUE THREAD

**Issue by yellowbeango** [walidamamou/relation_extraction_transformer#2]
Hi, thanks for your code and documents, but I think the binary_converter.py has errors, could you please update it? I saw UBIAI has a lot of export formats, which one is most convenient for using in SpaCy? Thanks so much!

**Comment by fernandonjardim** [comment]
Hi @walidamamou !
First of all great article! Thanks very much!

looking on your code, you got:

ann = "path_to/relation_training.txt"
train_file='path_to/relations_training.spacy'
dev_file='path_to/relations_dev.spacy'
test_file='path_to/relations_test.spacy'

But if I run the this converter, it actually only gets the relation_training.txt and generates the relations_training.spacy, right?

So to get dev_file and test_file, you have to run the code more two times, using dev and test.txt to convert to .spacy right?
